### ISSUE TITLE
上下左右四个角有黑色弧线

### ISSUE THREAD

**Issue by chuangWu** [Mosect/AShadow#1]
<LinearLayout
        android:layout_marginLeft="50dp"
        android:layout_marginRight="50dp"
        android:layout_marginTop="50dp"
        app:layout_shadowColor="#22000000"
        app:layout_roundRadius="15dp"
        app:layout_shadowRadius="10dp"
        android:layout_width="match_parent"
        android:layout_height="169dp"
        android:orientation="vertical">

将上面的布局代码放入ShadowLayout内部，运行Demo即可出现。

**Comment by Mosect** [comment]
使用最新jcenter开源库：
implementation 'com.mosect.AShadow:1.0.2'
添加以下属性：
app:layout_clipShadow="false"
app:layout_solidColor="控件背景色，不能是透明色"
solidColor表示填充的颜色，clipShadow表示不选定区域
