### ISSUE TITLE
布局预览问题

### ISSUE THREAD

**Issue by Alvin3225** [Mosect/AShadow#2]
直接down下来项目运行，在布局预览显示错误

java.io.StreamCorruptedException: invalid stream header: 01020209   at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:866)   at java.io.ObjectInputStream.<init>(ObjectInputStream.java:358)   at android.graphics.NinePatch_Delegate.getChunk(NinePatch_Delegate.java:114)   at android.graphics.BaseCanvas_Delegate.nDrawNinePatch(BaseCanvas_Delegate.java:397)   at android.graphics.BaseCanvas.nDrawNinePatch(BaseCanvas.java:-1)   at android.graphics.BaseCanvas.drawPatch(BaseCanvas.java:285)   at android.graphics.Canvas.drawPatch(Canvas.java:1703)   at android.graphics.NinePatch.draw(NinePatch.java:212)   at com.mosect.ashadow.RoundShadow.draw(RoundShadow.java:140)   at com.mosect.ashadow.ShadowHelper.drawShadow(ShadowHelper.java:176)   at com.mosect.ashadow.ShadowHelper.drawChildShadow(ShadowHelper.java:200)   at com.mosect.ashadow.ShadowLayout.drawChild(ShadowLayout.java:131)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)   at android.view.View.draw_Original(View.java:20210)   at android.view.View_Delegate.draw(View_Delegate.java:56)   at android.view.View.draw(View.java:20177)   at android.view.View.draw_Original(View.java:20077)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:19849)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)   at android.view.View.draw_Original(View.java:20075)   at android.view.View_Delegate.draw(View_Delegate.java:68)   at android.view.View.draw(View.java:19849)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4333)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:65)   at android.view.ViewGroup.drawChild(ViewGroup.java:4333)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)   at android.view.View.draw_Original(View.java:20210)   at android.view.View_Delegate.draw(View_Delegate.java:56)   at android.view.View.draw(View.java:20177)

**Comment by Mosect** [comment]
你好，布局预览已修复。请使用2.0.5；因预览工具本身不支持阴影效果，因此预览只是显示填充色和圆角
