### ISSUE TITLE
引用不到

### ISSUE THREAD

**Issue by sundahao** [Mosect/AShadow#5]
无法引用到2.0.5和2.0.4，其他版本没有测试

**Comment by Mosect** [comment]
Readme中有错误，试试下面的
implementation 'com.mosect:AShadow:2.0.5'

**Comment by Mosect** [comment]
> 无法引用到2.0.5和2.0.4，其他版本没有测试

Readme中有错误，试试下面的
implementation 'com.mosect:AShadow:2.0.5'
